config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  devise_for :users

  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end

  root 'posts#index'

  get ':username', to: 'profiles#show', as: :profile

  get ':username/edit', to: 'profiles#edit', as: :edit_profile

  patch ':username/edit', to: 'profiles#update', as: :update_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  has_attached_file :image, styles: { medium: "640x"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :user_id, presence: true
  validates :image, presence: true
  validates :caption, length: {minimum:3, maximum:300}

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  has_attached_file :image, styles: { medium: "640x"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, presence: true, length: { minimum: 4, maximum: 16}, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.js
      end
    else
      flash.now[:alert] = "Your comment couldn't be created. Please check the form."
      render root_path
    end
  end

  def index
    @comments = @post.comments.order("created_at ASC")

    respond_to do |format|
      format.html { render layout: !request.xhr?}
    end

  end

  def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def index
    @comments = comments.search(params)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :authenticate_user!
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC').page params[:page]
  end

  def new
    @post = current_user.posts.build
  end

  def show
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Your post has been created"
      redirect_to posts_path
    else
      flash.now[:alert] = "Your post couldn't be created. Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to @post
    else
      flash.now[:alert] = "Update failed. Please check the form."
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: "Successfully deleted post"
  end

  def like
    if @post.liked_by current_user
      respond_to do |format|
        format.html {redirect_to :back}
        format.js
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:caption, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless current_user == @post.user
      flash.now[:alert] = "Unauthorized."
      redirect_to root_path
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update, :destroy]

  def show
    @posts = @user.posts.order('created_at DESC')
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated."
      redirect_to profile_path(@user.username)
    else
      @user.errors.full_messages
      flash[:error] = @user.error.full_messages
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:bio, :image)
  end

  def set_user
    @user = User.find_by(:username => params[:username])
  end

  def owned_profile
    unless current_user == @user
      flash[:alert] = "Unauthorized."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def profile_image_select(user)
    if user.image.exists?
      image_tag user.image.url(:medium), id: 'image-preview', class: 'img-responsive img-circle profile-image'
    else
     image_tag 'default-image.png', id: 'image-preview', class: 'img-responsive img-circle profile-image'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def likers_of(post)
  votes = post.votes_for.up.by_type(User)
    usernames = []
    byebug
    unless votes.blank?
      votes.voters.each do |voter|
        usernames.push(link_to voter.username, profile_path(voter.username), class: 'username')
    end
          usernames.to_sentence.html_safe + like_plural(votes)
        end
    end
    private
      def like_plural(votes)
        return ' like this' if votes.count > 1
        ' likes this'
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.haml
#comment
  .user-name
    = link_to comment.user.username, profile_path(comment.user.username)
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete,
data: { confirm: "Are you sure?" }, remote:true do
      %span(class="glyphicon glyphicon-remove delete-comment-icon")

app/views/comments/create.js.erb
$('#comment_content_<%= @post.id %>').val('')
$('#comment_content_<%= @post.id %>').blur();
Append.comment_count += 1
$(Append.id).attr('data-value', Append.comment_count);
if (Append.comment || Append.open ){ $('#comments_<%= @post.id%>').append("<%=j render 'comments/comment', post: @post, comment:@comment %>"); }
else if ((Append.comment && Append.open) === false && Append.link ===
true) {
    $('#comments_' + Append.post_id).append("<div class='paginator'id='#comments-paginator-"
    + Append.post_id + "'><a class='more-comments' id='more_comments_" + Append.post_id + "' data-post-id='" +
Append.post_id + "' data-type='html' data-remote='true' data-value='"
+ Append.comment_count + "' href='/posts/" + Append.post_id +
"/comments'>view all " + Append.comment_count + " comments</a></div>");
    ClickableCommentsLink();
}
else if ((Append.comment && Append.open && Append.link) === false) {
$('#more_comments_<%= @post.id %>').html("view all <%=@post.comments.count %> comments"); }

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments,post: @post, comment: @comment %>");
Append.comment_count -= 1

app/views/comments/index.html.haml
= render @comments, post: @post

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "Mockogram", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to "My profile", profile_path(current_user.username)
          %li
            = link_to "New Post", new_post_path
          %li
            = link_to "Logout", destroy_user_session_path, :method => :delete

        - else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Mockogram
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

%body
  =render '/layouts/navbar'
  -flash.each do |name, msg|
    .container
    = content_tag :div, msg, class: [:alert, alert_for(name)]
  = yield

app/views/posts/_form.html.haml
.post-wrapper
  .posts
    .post-body
      .image-wrap
        - if @post.id.nil?
          = image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive'
        = simple_form_for @post, html: {class: 'form-horizontal', multipart:true} do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container.new-post-container
            .form-group.text-center
              %h4 Upload an image (this is required):
              = f.input :image, label:false, input_html: {onChange: 'loadFile(event)'}
            .form-group.text-center
              = f.input :caption, label:false, placeholder: "Add your caption", input_html: {class: 'form-control'}
            .form-group.text-center
              = f.button :submit, class: "btn-success btn-block"

app/views/posts/_likes.html.haml
-# .likes
-#   = likers_of post

app/views/posts/_post.html.haml
.posts-wrapper.row
  .post
    .post-head
      .thumb-img
      .user-name
        = link_to post.user.username, profile_path(post.user.username)
      .time-ago
        = time_ago_in_words(post.created_at)
    .image.center-block
      =link_to (image_tag post.image.url(:medium), class: 'img-responsive'), post_path(post)
    .post-bottom
      = render 'posts/likes', post: post
      .caption
        .caption-content
          .user-name
            = link_to post.user.username, profile_path(post.user.username)
          = post.caption
          .comments{id: "comments_#{post.id}"}
            - if post.comments.any?
              = render post.comments.first(4), post: post
              -unless post.comments.count <= 4
                .paginator{id: "comments-paginator-#{post.id}"}
                  =link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', id: "more_comments_#{post.id}", data: {post_id: "#{post.id}", type: "html", value: "#{post.comments.count}"}
      .comment-like-form.row
        .col-sm-1
          =link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}", class: "glyphicon glyphicon-heart-empty"
        .comment-form.col-sm-11
          = form_for([post, post.comments.build], remote: true) do |f|
            = f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"

app/views/posts/_posts.html.haml
-@posts.each do |post|
  = render 'post', post: post

app/views/posts/edit.html.haml
.text-center
  = image_tag @post.image.url(:medium)

= render 'form'

.text-center.edit-links
  = link_to "Delete Post", post_path, method: :delete, data:{confirm:"Are you sure?"}
  |
  = link_to "Cancel", posts_path

app/views/posts/index.html.haml
#posts
  = render 'posts'

#paginator.text-center
  = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts,'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
= render 'post', post: @post

- if @post.user_id == current_user.id
  .text-center.edit-links
    = link_to "Cancel", posts_path
    |
    = link_to "Edit Post", edit_post_path(@post)
- else
  .text-center.edit-links
    = link_to "Cancel", posts_path

app/views/profiles/edit.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_for @user, url: {action: "update"}, html: { multipart: true } do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your profile image:
                .img-circle
                  = profile_image_select(@user)
                  = f.file_field :image, onChange: 'loadFile(event)'
          .row
            .col-md-12
              .form-group.text-center
                %h4 Update your bio:
                = f.text_area :bio, label: false, rows: 4
          .form-group.text-center
            = f.submit "Update Profile", class: 'btn btn-success'

app/views/profiles/show.html.haml
.posts-wrapper
  .row.profile-header
    .col-md-6
      .img-circle
        = profile_image_select(@user)
    .col-md-6
      .user-name-and-follow
        %h3.profile-user-name
          = @user.username
        %span
          - if @user == current_user
            = link_to 'Edit Profile', edit_profile_path(@user.username), class: 'btn edit-button'
      %p.profile-bio
        = @user.bio
      .user-statistics
        %p
          = pluralize @user.posts.count, 'post'


- @posts.each do |post|
  = render 'posts/post', post: post